let pilotos = [
    {
        color: "wil",
        img: "https://media.formula1.com/image/upload/v1712849104/content/dam/fom-website/drivers/2024Drivers/albon.png",
        nome: "Alexander Albon",
        equipe: "Williams",
        pais: "Tailândia",
        nasc: "23/03/1996",
        numero: 23,
        pontos: 6,
        vitorias: 0,
        podios: 0,
        posicao: 17,
        insta: "https://www.instagram.com/alex_albon/"
},
    {
        color: "am",
        img: "https://media.formula1.com/image/upload/v1712849101/content/dam/fom-website/drivers/2024Drivers/alonso.png",
        nome: "Fernando Alonso",
        equipe: "Aston Martin",
        pais: "Espanha",
        nasc: "29/07/1981",
        numero: 14,
        pontos: 50,
        vitorias: 0,
        podios: 0,
        posicao: 9,
        insta: "https://www.instagram.com/fernandoalo_oficial/"
},
    {
        color: "sks",
        img: "https://media.formula1.com/image/upload/f_auto,c_limit,q_75,w_1320/content/dam/fom-website/drivers/2024Drivers/bottas",
        nome: "Valtteri Bottas",
        equipe: "Kick Sauber",
        pais: "Finlândia",
        nasc: "28/08/1989",
        numero: 77,
        pontos: 0,
        vitorias: 0,
        podios: 0,
        posicao: 22,
        insta: "https://www.instagram.com/valtteribottas/"
},
    {
        color: "wil",
        img: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/drivers/2024Drivers/colapinto",
        nome: "Franco Colapinto",
        equipe: "Williams",
        pais: "Argentina",
        nasc: "27/05/2003",
        numero: 43,
        pontos: 6,
        vitorias: 0,
        podios: 0,
        posicao: 21,
        insta: "https://www.instagram.com/francolapinto/"
},
    {
        color: "alp",
        img: "https://media.formula1.com/image/upload/f_auto,c_limit,q_75,w_1320/content/dam/fom-website/drivers/2024Drivers/gasly",
        nome: "Pierre Gasly",
        equipe: "Alpine",
        pais: "França",
        nasc: "07/02/1996",
        numero: 10,
        pontos: 8,
        vitorias: 0,
        podios: 0,
        posicao: 14,
        insta: "https://www.instagram.com/pierregasly/"
},
    {
        color: "mp",
        img: "https://media.formula1.com/image/upload/f_auto,c_limit,q_75,w_1320/content/dam/fom-website/drivers/2024Drivers/hamilton",
        nome: "Lewis Hamilton",
        equipe: "Mercedes",
        pais: "Reino Unido",
        nasc: "07/01/1985",
        numero: 44,
        pontos: 164,
        vitorias: 2,
        podios: 4,
        posicao: 6,
        insta: "https://www.instagram.com/lewishamilton/"
},
    {
        color: "haas",
        img: "https://media.formula1.com/image/upload/f_auto,c_limit,q_75,w_1320/content/dam/fom-website/drivers/2024Drivers/hulkenberg",
        nome: "Nico Hulkenberg",
        equipe: "Haas",
        pais: "Alemanha",
        nasc: "19/08/1987",
        numero: 27,
        pontos: 22,
        vitorias: 0,
        podios: 0,
        posicao: 11,
        insta: "https://www.instagram.com/hulkhulkenberg/"
},
    {
        color: "sf",
        img: "https://media.formula1.com/image/upload/f_auto,c_limit,q_75,w_1320/content/dam/fom-website/drivers/2024Drivers/leclerc",
        nome: "Charles Leclerc",
        equipe: "Ferrari",
        pais: "Mônaco",
        nasc: "16/10/1997",
        numero: 16,
        pontos: 217,
        vitorias: 2,
        podios: 8,
        posicao: 3,
        insta: "https://www.instagram.com/charles_leclerc/"
},
    {
        color: "haas",
        img: "https://media.formula1.com/image/upload/f_auto,c_limit,q_75,w_1320/content/dam/fom-website/drivers/2024Drivers/magnussen",
        nome: "Kevin Magnussen",
        equipe: "Haas",
        pais: "Dinamarca",
        nasc: "05/10/1992",
        numero: 20,
        pontos: 6,
        vitorias: 0,
        podios: 0,
        posicao: 16,
        insta: "https://www.instagram.com/kevinmagnussen/"
},
    {
        color: "mcl",
        img: "https://media.formula1.com/image/upload/f_auto,c_limit,q_75,w_1320/content/dam/fom-website/drivers/2024Drivers/norris",
        nome: "Lando Norris",
        equipe: "McLaren",
        pais: "Reino Unido",
        nasc: "13/11/1999",
        numero: 4,
        pontos: 241,
        vitorias: 2,
        podios: 10,
        posicao: 2,
        insta: "https://www.instagram.com/landonorris/"
},
    {
        color: "alp",
        img: "https://media.formula1.com/image/upload/f_auto,c_limit,q_75,w_1320/content/dam/fom-website/drivers/2024Drivers/ocon",
        nome: "Esteban Ocon",
        equipe: "Alpine",
        pais: "França",
        nasc: "17/09/1996",
        numero: 31,
        pontos: 5,
        vitorias: 0,
        podios: 0,
        posicao: 18,
        insta: "https://www.instagram.com/estebanocon/"
},
    {
        color: "rbr",
        img: "https://media.formula1.com/image/upload/f_auto,c_limit,q_75,w_1320/content/dam/fom-website/drivers/2024Drivers/perez",
        nome: "Sergio Perez",
        equipe: "Red Bull Racing",
        pais: "México",
        nasc: "26/01/1990",
        numero: 11,
        pontos: 143,
        vitorias: 0,
        podios: 4,
        posicao: 7,
        insta: "https://www.instagram.com/schecoperez/"
},
    {
        color: "mcl",
        img: "https://media.formula1.com/image/upload/f_auto,c_limit,q_75,w_1320/content/dam/fom-website/drivers/2024Drivers/piastri",
        nome: "Oscar Piastri",
        equipe: "McLaren",
        pais: "Austrália",
        nasc: "06/04/2001",
        numero: 81,
        pontos: 197,
        vitorias: 1,
        podios: 5,
        posicao: 4,
        insta: "https://www.instagram.com/oscarpiastri/"
},
    {
        color: "rb",
        img: "https://media.formula1.com/image/upload/f_auto,c_limit,q_75,w_1320/content/dam/fom-website/drivers/2024Drivers/ricciardo",
        nome: "Daniel Ricciardo",
        equipe: "RB",
        pais: "Austrália",
        nasc: "01/07/1989",
        numero: 3,
        pontos: 12,
        vitorias: 0,
        podios: 0,
        posicao: 13,
        insta: "https://www.instagram.com/danielricciardo/"
},
    {
        color: "mp",
        img: "https://media.formula1.com/image/upload/f_auto,c_limit,q_75,w_1320/content/dam/fom-website/drivers/2024Drivers/russell",
        nome: "George Russell",
        equipe: "Mercedes",
        pais: "Reino Unido",
        nasc: "15/02/1998",
        numero: 63,
        pontos: 128,
        vitorias: 1,
        podios: 2,
        posicao: 8,
        insta: "https://www.instagram.com/georgerussell63/"
},
    {
        color: "sf",
        img: "https://media.formula1.com/image/upload/f_auto,c_limit,q_75,w_1320/content/dam/fom-website/drivers/2024Drivers/sainz",
        nome: "Carlos Sainz",
        equipe: "Ferrari",
        pais: "Espanha",
        nasc: "01/09/1994",
        numero: 55,
        pontos: 184,
        vitorias: 1,
        podios: 5,
        posicao: 5,
        insta: "https://www.instagram.com/carlossainz55/"
},
    {
        color: "am",
        img: "https://media.formula1.com/image/upload/f_auto,c_limit,q_75,w_1320/content/dam/fom-website/drivers/2024Drivers/stroll",
        nome: "Lance Stroll",
        equipe: "Aston Martin",
        pais: "Canadá",
        nasc: "29/10/1998",
        numero: 18,
        pontos: 24,
        vitorias: 0,
        podios: 0,
        posicao: 10,
        insta: "https://www.instagram.com/lance_stroll/"
},
    {
        color: "rb",
        img: "https://media.formula1.com/image/upload/f_auto,c_limit,q_75,w_1320/content/dam/fom-website/drivers/2024Drivers/tsunoda",
        nome: "Yuki Tsunoda",
        equipe: "RB",
        pais: "Japão",
        nasc: "11/05/2000",
        numero: 22,
        pontos: 22,
        vitorias: 0,
        podios: 0,
        posicao: 12,
        insta: "https://www.instagram.com/yukitsunoda0511/"
},
    {
        color: "rbr",
        img: "https://media.formula1.com/image/upload/f_auto,c_limit,q_75,w_1320/content/dam/fom-website/drivers/2024Drivers/verstappen",
        nome: "Max Verstappen",
        equipe: "Red Bull Racing",
        pais: "Holanda",
        nasc: "30/09/1997",
        numero: 1,
        pontos: 303,
        vitorias: 7,
        podios: 10,
        posicao: 1,
        insta: "https://www.instagram.com/maxverstappen1/"
},
    {
        color: "sks",
        img: "https://media.formula1.com/image/upload/f_auto,c_limit,q_75,w_1320/content/dam/fom-website/drivers/2024Drivers/zhou",
        nome: "Zhou Guanyu",
        equipe: "Kick Sauber",
        pais: "China",
        nasc: "30/05/1999",
        numero: 24,
        pontos: 6,
        vitorias: 0,
        podios: 0,
        posicao: 19,
        insta: "https://www.instagram.com/zhouguanyu24/"
},
    {
        color: "wil",
        img: "https://media.formula1.com/image/upload/f_auto,c_limit,q_75,w_1320/content/dam/fom-website/drivers/2024Drivers/sargeant",
        nome: "Logan Sargeant",
        equipe: "Williams",
        pais: "EUA",
        nasc: "31/12/2000",
        numero: 2,
        pontos: 0,
        vitorias: 0,
        podios: 0,
        posicao: 20,
        insta: "https://www.instagram.com/logansargeant/"
},
{
    color: "sf",
    img: "https://media.formula1.com/d_driver_fallback_image.png/content/dam/fom-website/drivers/O/OLIBEA01_Oliver_Bearman/olibea01.png",
    nome: "Oliver Bearman",
    equipe: "Ferrari",
    pais: "Reino Unido",
    nasc: "08/05/2005",
    numero: 38,
    pontos: 6,
    vitorias: 0,
    podios: 0,
    posicao: 15,
    insta: "https://www.instagram.com/olliebearman/" 
}
];

let equipes = [
    {
        color: "rbr",
        img: "https://media.formula1.com/image/upload/f_auto,c_limit,q_75,w_1320/content/dam/fom-website/2018-redesign-assets/team%20logos/red%20bull",
        nomeEquipe: "Red Bull Racing",
        nomeCompleto: "Oracle Red Bull Racing",
        base: "Milton Keynes, Reino Unido",
        chefe: "Christian Horner",
        motor: "Honda RBPT",
        chassi: "RB20",
        piloto: "Verstappen e Perez",
        pontos: 446,
        posicao: 1,
        insta: "https://www.instagram.com/redbullracing/"
},
    {
        color: "mcl",
        img: "https://media.formula1.com/image/upload/f_auto,c_limit,q_75,w_1320/content/dam/fom-website/2018-redesign-assets/team%20logos/mclaren",
        nomeEquipe: "McLaren",
        nomeCompleto: "McLaren Formula 1 Team",
        base: "Woking, Reino Unido",
        chefe: "Andrea Stella",
        motor: "Mercedes",
        chassi: "MCL38",
        piloto: "Norris e Piastri",
        pontos: 438,
        posicao: 2,
        insta: "https://www.instagram.com/mclaren/"
},
    {
        color: "sf",
        img: "https://media.formula1.com/image/upload/f_auto,c_limit,q_auto,w_1320/content/dam/fom-website/2018-redesign-assets/team%20logos/ferrari",
        nomeEquipe: "Ferrari",
        nomeCompleto: "Scuderia Ferrari",
        base: "Maranello, Itália",
        chefe: "Frédéric Vasseur",
        motor: "Ferrari",
        chassi: "SF-24",
        piloto: "Leclerc e Sainz",
        pontos: 407,
        posicao: 3,
        insta: "https://www.instagram.com/scuderiaferrari/"
},
    {
        color: "mp",
        img: "https://media.formula1.com/image/upload/f_auto,c_limit,q_75,w_1320/content/dam/fom-website/2018-redesign-assets/team%20logos/mercedes",
        nomeEquipe: "Mercedes",
        nomeCompleto: "Mercedes-AMG PETRONAS F1 Team",
        base: "Brackley, Reino Unido",
        chefe: "Toto Wolff",
        motor: "Mercedes",
        chassi: "W15",
        piloto: "Verstappen e Perez",
        pontos: 292,
        posicao: 4,
        insta: "https://www.instagram.com/mercedesamgf1/"
},
{
    color: "am",
    img: "https://media.formula1.com/image/upload/f_auto,c_limit,q_75,w_1320/content/dam/fom-website/2018-redesign-assets/team%20logos/aston%20martin%202024",
    nomeEquipe: "Aston Martin",
    nomeCompleto: "Aston Martin Aramco F1 Team",
    base: "Silverstone, Reino Unido",
    chefe: "Mike Krack",
    motor: "Mercedes",
    chassi: "AMR24",
    piloto: "Alonso e Stroll",
    pontos: 74,
    posicao: 5,
    insta: "https://www.instagram.com/astonmartinf1/"
},
{
    color: "rb",
    img: "https://media.formula1.com/image/upload/f_auto,c_limit,q_75,w_1320/content/dam/fom-website/2018-redesign-assets/team%20logos/rb",
    nomeEquipe: "RB",
    nomeCompleto: "Visa Cash App RB Formula One Team",
    base: "Faenza, Itália",
    chefe: "Laurent Mekies",
    motor: "Honda RBPT",
    chassi: "VCARB 01",
    piloto: "Tsunoda e Ricciardo",
    pontos: 34,
    posicao: 6,
    insta: "https://www.instagram.com/visacashapprb/"
},
{
    color: "haas",
    img: "https://media.formula1.com/image/upload/f_auto,c_limit,q_75,w_1320/content/dam/fom-website/2018-redesign-assets/team%20logos/haas",
    nomeEquipe: "Haas",
    nomeCompleto: "MoneyGram Haas F1 Team",
    base: "Kannapolis, Estados Unidos",
    chefe: "Ayao Komatsu",
    motor: "Ferrari",
    chassi: "VF-24",
    piloto: "Hulkenberg e Magnussen",
    pontos: 28,
    posicao: 7,
    insta: "https://www.instagram.com/haasf1team/"
},
{
    color: "alp",
    img: "https://media.formula1.com/image/upload/f_auto,c_limit,q_75,w_1320/content/dam/fom-website/2018-redesign-assets/team%20logos/alpine",
    nomeEquipe: "Alpine",
    nomeCompleto: "BWT Alpine F1 Team",
    base: "Enstone, Reino Unido",
    chefe: "Oliver Oakes",
    motor: "Renault",
    chassi: "A524",
    piloto: "Gasly e Ocon",
    pontos: 13,
    posicao: 8,
    insta: "https://www.instagram.com/alpinef1team/"
},
{
    color: "wil",
    img: "https://media.formula1.com/image/upload/f_auto,c_limit,q_75,w_1320/content/dam/fom-website/2018-redesign-assets/team%20logos/williams",
    nomeEquipe: "Williams",
    nomeCompleto: "Williams Racing",
    base: "Grove, Reino Unido",
    chefe: "James Vowles",
    motor: "Mercedes",
    chassi: "FW46",
    piloto: "Albon e Colapinto",
    pontos: 6,
    posicao: 9,
    insta: "https://www.instagram.com/williamsracing/"
},
{
    color: "sks",
    img: "https://media.formula1.com/image/upload/f_auto,c_limit,q_75,w_1320/content/dam/fom-website/2018-redesign-assets/team%20logos/kick%20sauber",
    nomeEquipe: "Kick Sauber",
    nomeCompleto: "Stake F1 Team Kick Sauber",
    base: "Hinwil, Suíça",
    chefe: "Alessandro Alunni Bravi",
    motor: "Ferrari",
    chassi: "C44",
    piloto: "Bottas e Zhou",
    pontos: 0,
    posicao: 10,
    insta: "https://www.instagram.com/stakef1team/"
}
];